#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove surfaces and features
rm -rf SiphonCup_0.001.stl
rm -rf constant/triSurface
rm -rf constant/extendedFeatureEdgeMesh

#------------------------------------------------------------------------------
